name: deploy-py-lambda
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Zip Lambda
      run: cd src && zip -r ../lambda.zip .
    - name: Deploy Lambda
      run: aws lambda update-function-code --function-name ralph --zip-file fileb://lambda.zip
    - name: Update Lambda Env Vars
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ env.REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DYNAMO_TABLE_NAME: ${{ env.DYNAMO_TABLE_NAME }}
        LOG_LEVEL: ${{ env.LOG_LEVEL }}
        REGION: ${{ env.REGION }}
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      run: |
        aws lambda update-function-configuration \
          --function-name ralph \
          --environment "Variables={DYNAMO_TABLE_NAME=${DYNAMO_TABLE_NAME},LOG_LEVEL=${LOG_LEVEL},REGION=${REGION},SLACK_API_TOKEN=${SLACK_API_TOKEN}}"
